package View;

import Model.JogoVariavel;
import View.NovoJogo;
import javax.swing.JOptionPane;
import View.Login;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Lorenzo
 */
public class ForcaInterface extends javax.swing.JFrame {

    /**
     * Creates new form ForcaInterface
     */
    public ForcaInterface() {
        initComponents();

    }

    //Exibir a palavra na tela
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChuteLetra1 = new javax.swing.JButton();
        btnChuteLetra2 = new javax.swing.JButton();
        lblCorpo = new javax.swing.JPanel();
        btnChuteLetra = new javax.swing.JButton();
        btnNovoJogo = new javax.swing.JButton();
        btnChutePalavra = new javax.swing.JButton();
        cbPalavra = new javax.swing.JComboBox<>();
        btnNuncaeumAdeus = new javax.swing.JButton();
        lblLetra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();

        btnChuteLetra1.setText("Chutar letra");
        btnChuteLetra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuteLetra1ActionPerformed(evt);
            }
        });

        btnChuteLetra2.setText("Chutar letra");
        btnChuteLetra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuteLetra2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCorpo.setBackground(new java.awt.Color(187, 187, 187));

        btnChuteLetra.setText("Chutar palavra");
        btnChuteLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuteLetraActionPerformed(evt);
            }
        });

        btnNovoJogo.setText("Novo Jogo");
        btnNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoJogoActionPerformed(evt);
            }
        });

        btnChutePalavra.setText("Chutar Palavra");
        btnChutePalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChutePalavraActionPerformed(evt);
            }
        });

        cbPalavra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abstraçao", "Algoritmo", "API", "Arquitetura", "Arquivo", "Array", "ArrayList", "Banco de Dados", "BigDecimal", "Branch", "Classe", "ClassCastException", "Cliente", "Compilaçao", "Compilador", "Commit", "Conexao", "Construtor", "Console", "Condicional", "Debug", "Deserialization", "Enum", "Entrada", "Exceçao", "Eclipse", "Exceçao", "File", "Framework", "Funçao", "Git", "Gradle", "HashMap", "Herança", "Hibernate", "IDE", "Instancia", "Interface", "JDK", "Java", "JavaFX", "JPA", "JSP", "JUnit", "JSON", "Lambda", "List", "LinkedList", "Loop", "Map", "Maven", "Merge", "Microservices", "Metodo", "NullPointerException", "Object", "Objeto", "POO", "Parametro", "Persistancia", "Polimorfismo", "Passiencia", "Performance", "Pull", "Recursao", "Refatoraçao", "Reflection", "Repositario", "Retorno", "REST", "Scala", "Set", "Sincronizaçao", "Servidor", "Servlet", "Sintaxe", "SQL", "Stack", "Stream", "String", "Spring", "Swing", "Teste", "TestUnit", "Thread", "Tipagem", "Tomcat", "Variável", "WebSocket", "XML", "Queue", "Socket", "Serialization", "SQLException", "Stack", "Reflection", "Maven" }));
        cbPalavra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPalavraActionPerformed(evt);
            }
        });

        btnNuncaeumAdeus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuncaeumAdeus.setText("NUNCA É UM ADEUS!?");
        btnNuncaeumAdeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuncaeumAdeusActionPerformed(evt);
            }
        });

        jLabel1.setText("Letra chutada:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("JOGO DA FORCA");

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/forca.png"))); // NOI18N

        javax.swing.GroupLayout lblCorpoLayout = new javax.swing.GroupLayout(lblCorpo);
        lblCorpo.setLayout(lblCorpoLayout);
        lblCorpoLayout.setHorizontalGroup(
            lblCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblCorpoLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(btnNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(lblCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblCorpoLayout.createSequentialGroup()
                        .addComponent(btnNuncaeumAdeus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(lblCorpoLayout.createSequentialGroup()
                        .addGroup(lblCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblCorpoLayout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(lblLetra))
                            .addGroup(lblCorpoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnChuteLetra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)))
                .addComponent(btnChutePalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(lblCorpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagem)
                .addGap(89, 89, 89)
                .addGroup(lblCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblCorpoLayout.setVerticalGroup(
            lblCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblCorpoLayout.createSequentialGroup()
                .addGroup(lblCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblCorpoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagem))
                    .addGroup(lblCorpoLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(lblCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLetra)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChuteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChutePalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnNuncaeumAdeus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCorpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCorpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChuteLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuteLetraActionPerformed

        //Exibir no Label da palavra selecionada na tela
        JogoVariavel jv = new JogoVariavel();
        lblLetra.setText(cbPalavra.getSelectedItem().toString());

        // Verificar se a palavra escolhida no comboBox é igual a palavra da forca para saber se acertou ou nâo
        if (jv.getPalavraCb().toUpperCase().equals(cbPalavra.getSelectedItem().toString().toUpperCase())) {
            JOptionPane.showMessageDialog(this, "Parabens, você acertou!! \tA palavra é '" + jv.getPalavraCb().toUpperCase() + "'");

        } else {
            jv.diminuirTentativas(); //Diminui as tentativas da pessoa

            //Se as tentativas forem = 0, você perde o jogo
            if (jv.getTentativaLabel() == 0) {
                JOptionPane.showMessageDialog(this, "Voce perdeu \tA palavra correta éra: " + "'" + jv.getPalavraCb().toUpperCase() + "'");
                ForcaInterface.this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Voce possui " + jv.getTentativaLabel() + " tentativas."); //Mostrar quantia de tentativas você possui
            }
        }
    }//GEN-LAST:event_btnChuteLetraActionPerformed

    private void btnChuteLetra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuteLetra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChuteLetra1ActionPerformed

    private void btnChuteLetra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuteLetra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChuteLetra2ActionPerformed

    private void btnNuncaeumAdeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuncaeumAdeusActionPerformed
        ForcaInterface.this.dispose();
    }//GEN-LAST:event_btnNuncaeumAdeusActionPerformed

    private void btnChutePalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChutePalavraActionPerformed

        //Abrir menu de chutar palavra da forca apartir do menu principal
        ChutePalavra chutepalavra = new ChutePalavra();
        chutepalavra.setLocationRelativeTo(chutepalavra);
        chutepalavra.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        chutepalavra.setVisible(true);
    }//GEN-LAST:event_btnChutePalavraActionPerformed

    private void cbPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPalavraActionPerformed


    }//GEN-LAST:event_cbPalavraActionPerformed

    private void btnNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoJogoActionPerformed

        //Abrir aba de novo jogo através do botão do menu principal
        NovoJogo novojogo = new NovoJogo();
        novojogo.setLocationRelativeTo(novojogo);
        novojogo.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        novojogo.setVisible(true);
        ForcaInterface.this.dispose();
    }//GEN-LAST:event_btnNovoJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForcaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForcaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForcaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForcaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                //abrir atela de login
                Login jl = new Login();

                //Centralizar na tela e deixar visivel
                jl.setLocationRelativeTo(jl);
                jl.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jl.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuteLetra;
    private javax.swing.JButton btnChuteLetra1;
    private javax.swing.JButton btnChuteLetra2;
    private javax.swing.JButton btnChutePalavra;
    private javax.swing.JButton btnNovoJogo;
    private javax.swing.JButton btnNuncaeumAdeus;
    private javax.swing.JComboBox<String> cbPalavra;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel lblCorpo;
    private javax.swing.JLabel lblLetra;
    // End of variables declaration//GEN-END:variables
}
