package View;

import Model.JogoVariavel;
import View.NovoJogo;

/**
 *
 * @author Lorenzo
 */
public class ForcaInterface extends javax.swing.JFrame {

    /**
     * Creates new form ForcaInterface
     */
    public ForcaInterface() {
        initComponents();
    }

    //Exibir a palavra na tela
    public void exportarPalavra(JogoVariavel variavel) {
        lblPalavra.setText(variavel.getPalavra());
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChuteLetra1 = new javax.swing.JButton();
        btnChuteLetra2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnChuteLetra = new javax.swing.JButton();
        btnNovoJogo = new javax.swing.JButton();
        btnChutePalavra = new javax.swing.JButton();
        cbLetra = new javax.swing.JComboBox<>();
        btnNuncaeumAdeus = new javax.swing.JButton();
        lblPalavra = new javax.swing.JLabel();
        lblCb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        btnChuteLetra1.setText("Chutar letra");
        btnChuteLetra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuteLetra1ActionPerformed(evt);
            }
        });

        btnChuteLetra2.setText("Chutar letra");
        btnChuteLetra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuteLetra2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(187, 187, 187));

        btnChuteLetra.setText("Chutar letra");
        btnChuteLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuteLetraActionPerformed(evt);
            }
        });

        btnNovoJogo.setText("Novo Jogo");
        btnNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoJogoActionPerformed(evt);
            }
        });

        btnChutePalavra.setText("Chutar Palavra");
        btnChutePalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChutePalavraActionPerformed(evt);
            }
        });

        cbLetra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        cbLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLetraActionPerformed(evt);
            }
        });

        btnNuncaeumAdeus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuncaeumAdeus.setText("NUNCA É UM ADEUS!?");
        btnNuncaeumAdeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuncaeumAdeusActionPerformed(evt);
            }
        });

        lblPalavra.setText("teste");

        lblCb.setText("..........");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Letra Chutada:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(btnNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuncaeumAdeus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnChuteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39)
                .addComponent(btnChutePalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(lblPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(lblPalavra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChuteLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChutePalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnNuncaeumAdeus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChuteLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuteLetraActionPerformed
//        JogoVariavel jv = new JogoVariavel();
//        for (int i = 0; i < jv.getPalavra().length(); i++) {
//  char letra = jv.getPalavra().charAt(i);
//  if (char.equals(cbLetra.getText)){
//    System.out.println("A palavra contem esta letra");
//  } else if (char.equals(" ")) {
//    System.out.println("A letra que voce chutou não tem na palavra.");
//  }
//}
        
    }//GEN-LAST:event_btnChuteLetraActionPerformed

    private void btnChuteLetra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuteLetra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChuteLetra1ActionPerformed

    private void btnChuteLetra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuteLetra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChuteLetra2ActionPerformed

    private void btnNuncaeumAdeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuncaeumAdeusActionPerformed
        ForcaInterface.this.dispose();
    }//GEN-LAST:event_btnNuncaeumAdeusActionPerformed

    private void btnNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoJogoActionPerformed
        //Abrir aba de novo jogo através do menu principal      
        NovoJogo novojogo = new NovoJogo();
        novojogo.setLocationRelativeTo(novojogo);
        novojogo.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        novojogo.setVisible(true);
        ForcaInterface.this.dispose();


    }//GEN-LAST:event_btnNovoJogoActionPerformed

    private void btnChutePalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChutePalavraActionPerformed
        //Abrir menu de chutar palavra da forca
        ChutePalavra chutepalavra = new ChutePalavra();
        chutepalavra.setLocationRelativeTo(chutepalavra);
        chutepalavra.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        chutepalavra.setVisible(true);
    }//GEN-LAST:event_btnChutePalavraActionPerformed

    private void cbLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLetraActionPerformed
        lblCb.setText(cbLetra.getSelectedItem().toString());

//        JogoVariavel jv = new JogoVariavel();
//        private static char[] cbLetra = new char[palavra.length()];
    }//GEN-LAST:event_cbLetraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForcaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForcaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForcaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForcaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

//abrir menu centralisado na tela
                ForcaInterface frame = new ForcaInterface();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuteLetra;
    private javax.swing.JButton btnChuteLetra1;
    private javax.swing.JButton btnChuteLetra2;
    private javax.swing.JButton btnChutePalavra;
    private javax.swing.JButton btnNovoJogo;
    private javax.swing.JButton btnNuncaeumAdeus;
    private javax.swing.JComboBox<String> cbLetra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCb;
    private javax.swing.JLabel lblPalavra;
    // End of variables declaration//GEN-END:variables
}
